NorthernTechHQ/libntech

configure.ac
Turns out you can't use shell variables in AC_INIT:
```
configure.ac:36: warning: AC_INIT: not a literal: $libntech_version
```
=> Switched to using autoconf AC_PACKAGE_VERSION variable

.clang-format
Correct according to our style guide.
=> clang-format: Add spaces after type casts

libutils/json.c, libutils/json.h
The container being iterated over should be read-only (to avoid
issues with iterating over a modifying structure). But the child
objects the iterator returns should be modifiabler/read-write,
changing those is not a problem.
=> Make JSON iterator return non-const JsonElement

configure.ac
It seems this variable already had a value, with the include
path of the header, so overwriting it here was a bad idea.
We should probably fix the line below as well, but I don't
know what's appropriate, and this patch was enough to fix
my problems when building on OpenBSD.
=> Fixed issue with including pcre.h on OpenBSD

libutils/Makefile.am
Should be part of dist tarball, but not compiled directly.
This commit makes it possible to run `make dist`, and then
`./configure && make` inside the expanded tarball, without
errors.
`stack_base.c` is not in `_SOURCES`, because it includes
static functions and definitions which are needed in both
`stack.c` and `threaded_stack.c`. Compiling it directly
would cause warnings about unused static functions.
This is also explained in `stack_base.c`:
```
/** @file stack_base.c
* @brief Shared code between threaded_stack.c and stack.c
*
* This file should be included, not compiled separately.
*/
```
=> Added stack_base.c to EXTRA_DIST

configure.ac, travis-scripts/after_success.sh
Previously, when explicit `CFLAGS`/`LDFLAGS` were set, they
would override the coverage flags from `configure.ac`
(`--enable-coverage`). Other similar flags are substituted using
the `CORE_CFLAGS`, `CORE_LDFLAGS`, etc. However, this was done
too early to capture the flags from `--enable-coverage`.
=> Travis: Fixed code coverage

libutils/threaded_deque.c, libutils/threaded_queue.c, libutils/threaded_stack.c
When compiling on Debian 6 (in core) errors were encountered,
because, on this platform, it's important to set some
OPEN_SOURCE macro before including `pthread.h`:
https://stackoverflow.com/questions/18375527/why-is-gnu-source-macro-required-for-pthread-mutexattr-settype-while-it-is-in
=> Include platform.h before pthread.h

tests/unit/Makefile.am
We need some extra include folders to be able to build in
environments where devel packages are installed in /var/cfengine.
=> Fix CPPFLAGS for the new file_locks_test unit tests

libutils/logging.c
It's using a buffer the size of which is specified as CF_BUFSIZE.
=> Add a missing include for GetErrorStr() on Windows

libutils/file_lib.c
They can use the same implementation because the functions they
use internally have OS-specific implementations.
=> Make Exclusive/SharedFileLockPath() functions avaiable on Windows

libutils/file_lib.c
Same as additions made in glibc. Check NOTES under `man 3 fopen`.
Ticket: None
=> Added O_EXCL for safe_fopen

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
This was a static function in core, called CloseStringHole().
Added asserts, tests, and a doxygen comment.
=> Added StringCloseHole() from core

libutils/json-utils.c, libutils/json-utils.h, libutils/json.h
Refactoring includes:
- Put `FileType` in `json-utils` and make it an enum instead
(previously just returned a string)
- Added utility function to get a string from the new enums
- Added JsonParseAnyFile to `json.h`. It wasn't static, and is
actually (slightly) useful outside `json.c`
Note that this needs to be merged with a libpromises patch that replaces
the use of `JsonReadDataFile`
Ticket: None
I was unsure of whether to split this into several commits or not. It should be fairly easy to review I think.
=> Refactor json-utils, put `JsonParseAnyFile` in json.h header

libutils/string_sequence.c
This was not really intended, and it is very useful to be able to keep writing to the file afterwards.
=> ENT-5313: SeqStringWriteFileStream() no longer closes FILE stream

libutils/json.c, libutils/json.h, libutils/mustache.c, tests/unit/json_test.c
When validating json, you usually want to know whether an
element is exactly the type it should be. First checking
ElementType and then PrimitiveType / ContainterType is tedious,
makes the code harder to read, and more prone to error.
Could be cleaned up in many places, but this is enough for now.
I want to use this in `classfilterdata()`.
=> Added enum JsonType and GetJsonType()

libutils/csv_writer.c, libutils/csv_writer.h, tests/unit/csv_writer_test.c
Useful for writing "single line csv", for use in reporting protocol.
=> ENT-4829: Added possibility to not terminate last line of CSV writer

libutils/mustache.c
Segmentation fault when it cannot find the end of a tag (tag.end).
Trying to dereference a NULL pointer when trying to render.
=> Fixed crash in mustache rendering when parser cannot find the end of a tag

libutils/mustache.c
The original fix, causes this policy to not crash (segfault):
```
bundle agent main
{
vars:
"blah"
with => string_mustache("{{");
}
```
This fix, also makes the mustache code pass unit tests in core, again.
=> Fixed the fix for mustache rendering

libutils/mustache.c
Previously, they were warnings.
According to core/CONTRIBUTING.md:
* `LOG_LEVEL_ERR`: Promise failed or other errors that are definitely
considered bad / not normal.
* `LOG_LEVEL_WARNING`: Something unusual happened that the user should
investigate. Should be severe enough to warrant investigating further,
but not as severe as a definitive error/bug.
I would argue that if you have a broken template, that definitely
warrants an error. It means there is a bug in your template, or
whatever is generating the template. Looking at `git blame` this
has been a warning since mustache was introduced, and there is no
specific reasoning behind it.
=> Log messages about broken Mustache templates are now errors

libutils/man.c, libutils/man.h, libutils/writer.c, libutils/writer.h
In many cases it's more natural to use
some-utility COMMAND OPTIONS
than
some-utility OPTIONS COMMAND.
For such cases, we want to adapt the --help/-h output.
Ticket: CFE-3272
=> Improved support for commands in help outputs and man pages

libutils/logging.c, libutils/logging.h
Log() does most of the heavy lifting of formatting the log
message like printf() only when the log level means the message
will actually be logged. But sometimes there is a lot of work
being done before Log() is even called. It is nice to have a
chance to tell if such work can be skipped because Log() would
just discard the result anyway.
=> Add a function for checking whether Log() would log a message

libutils/compiler.h
This functionality is also implemented by macro TOSTRING at string_lib.h
Ticket: None
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
=> compiler.h: remove duplicated macro

libutils/compiler.h, libutils/file_lib.c, libutils/string_lib.h, libutils/string_sequence.c
Makes more sense for this macro to live in compiler.h. Renamed to follow
coding standard.
Ticket: None
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
=> compiler.h: move, rename and document TO_STRING macro

libutils/definitions.h
This reverts commit a38d6130c34656ca235b3d9aebd08209dde1afcc.
The logic for group ownership is moved/refined in masterfiles instead.
This information in libntech is not very reliable so should not be included.
Ideally we would examine each system at run-time to determine the
default group for root. For now our "guesses" are in masterfiles https://github.com/cfengine/masterfiles/pull/1768
Conflicts:
libutils/definitions.h
=> Revert "Added CF_SYSTEM_GROUP based on ifdefs"

libutils/buffer.c, libutils/csv_writer.c, libutils/json-yaml.c, libutils/list.c, libutils/sequence.c, libutils/sequence.h
Gets the rid of a bunch of LGTM alerts. Minor style and consistency
fixes along the way.
=> misc files: Add explicit checks for NULL before pointer dereferences

libutils/platform.h
Gentoo has a stub header that spews:
> Please change your <attr/xattr.h> includes to <sys/xattr.h>
=> prefer <sys/xattr.h> over obsolete <attr/xattr.h>

libutils/json-utils.c, libutils/json.c, libutils/logging.c, libutils/map.c, libutils/mustache.c, libutils/set.c, libutils/string_lib.c, libutils/string_lib.h, libutils/string_sequence.c, tests/unit/hash_test.c, tests/unit/map_test.c, tests/unit/string_lib_test.c
This has annoyed me for quite some time.
There are many reasons to do this:
* It's shorter, faster to type and read and causes less line-splitting
* Safe should be default anyway, unsafe functions should be marked as such
* Easier to remember (Is it StringSafeEqual or SafeStringEqual?)
=> Renamed StringSafeEqual() to StringEqual()

libutils/ip_address.c, libutils/ip_address.h
More cases of functions and variables which should be bool.
AFAICT the -1 return value was unreachable anyway. (And it was
treated as bool in the calling location).
Also refactored IPAddressCompareLess() to follow code style,
fixed indentation, added assertions and comments to make it
easier to understand.
Reported by LGTM:
https://lgtm.com/rules/1508604166004/
=> Cleaned up IP address comparison functions

libutils/definitions.h
Placed them here because they have a loose relationship to
CF_MAXVARSIZE. Just constants, shouldn't hurt anyone.
=> CFE-3409 definitions.h: Added constant buffer sizes for DB names and table names

libutils/string_sequence.c, libutils/string_sequence.h, tests/unit/sequence_test.c
The length-prefixed format for (de)serialization of strings is
useful for more cases than just putting all the strings into a
sequence. Let's make the code available for such cases.
Ticket: ENT-5293
=> Make the code for (de)serialization of strings more reusable

libutils/json.c, libutils/json.h, libutils/string_lib.c, libutils/string_lib.h, tests/unit/json_test.c, tests/unit/sequence_test.c, tests/unit/string_lib_test.c
Generally in the CFEngine codebase we use `long`, but on some platforms, `long` is 32-bit. When you need to handle bigger numbers, using `int64_t` is better.
=> Functions for handling 64-bit numbers from JSON files

libutils/mustache.c
Example:
```
root@OH-WIN:/northern.tech/cfengine/core# cat test.cf
bundle agent firewall
{
vars:
"_defaults" data => '{ "source": "0.0.0.0/0", "protocol": "tcp" }';
"cfengine" data => mergedata( @(_defaults), '{"name": "cfengine" "destination-port": "5308" }' );
"RULES" data => mergedata( '{ "ACCEPT": [ cfengine ]}' );
reports:
"$(with)" with => string_mustache( "{{#ACCEPT}}{{.}}{{/ACCEPT}}", RULES );
}
bundle agent __main__
{
methods:
"firewall";
reports:
"CFEngine $(sys.cf_version)";
}
root@OH-WIN:/northern.tech/cfengine/core# /var/cfengine/bin/cf-agent -KI test.cf
warning: {{.}} mustache tag cannot expand a container without specifying conversion - consider {{$.}} or {{%.}}
warning: {{.}} mustache tag cannot expand a container without specifying conversion - consider {{$.}} or {{%.}} …
```
=> CFE-3489: Mustache: Added warning when trying to use {{.}} to expand containers

.travis.yml, libutils/buffer.c, libutils/string_lib.c
- .travis.yml : Added Arm64 jobs along with the installation of package require for arm64
- libutils/[buffer.c, string_lib.c]: Fixed strcmp() issue for arm64
- strcmp() has different behavior in arm64 and amd64. At ARM64, strcmp(char* a, char* b) returns the value other than 1 or -1, as per given char buffer inputs.
- While asserting buf_size in libutils/string_lib.c in line 65, added typecasting as in ARM64 'char' is considered as 'unsigned char' whereas AMD64 treats 'char' as 'signed char'
Signed-off-by: odidev <odidev@puresoftware.com>
=> Add ARM64 job in Travis-CI

libutils/platform.h
This made it more annoying to debug for me, since
the compiler would point me to the last (shared) line,
which doesn't have the relevant information (the return type).
=> Removed line split to ease debugging

libutils/platform.h
Necessary to try compiling with `-std=c11` in gcc, since
they are already defined then.
=> Don't redefine le32toh and htole32

libutils/platform.h
Line split was removed for `endnetgrent` below in commit c77a9a4 due to
annoyance while debugging. I'll do the same with `setnetgrent` for the
sake of consistancy.
Ticket: None
=> Removed line split to maintain consistancy

.gitignore, libutils/condition_macros.h, tests/unit/Makefile.am, tests/unit/condition_macros_test.c
```
nt_static_assert_string_equal(PATH_SEPARATOR, "/");
```
Is more readable than:
```
nt_static_assert(strcmp(PATH_SEPARATOR, "/") == 0);
```
Also added tests for both.
=> Added nt_static_assert_string_equal()

.github/workflows/asan_unit_tests.yml, .github/workflows/macos_unit_tests.yml
At first I was adding it to the same workflow as Ubuntu, but
this became ugly, since there are many differences. A separate
workflow (yml) makes it much cleaner.
Running with ASAN on MacOS requires some more work, but this gets us halfway there.
=> CFE-3540: GitHub Actions: Added MacOS Unit Tests

libutils/json.c, libutils/json.h
It is useful in code writing out JSON without actually creating
then JSON structures in memory (to avoid data duplication, etc.).
Ticket: ENT-6182
=> Make JsonEncodeStringWriter() a public function in libutils

libutils/string_lib.c
Variable of unsigned type was checked to be greater that zero.
Ticket: None
=> Removed unnecessary assert comparison

libutils/threaded_stack.c
To make sure the process is killed in case of no memory left
instead of trying to work with NULL returned from malloc().
=> Always use xmalloc() in threaded_stack.c

libutils/compiler.h
Sometimes a variables is only used in an assertion like
'assert(ret > 0)` which results in a compilation warning/error
when compiling without '--enable-debug' because in such cases
all 'assert()' are removed.
=> Add a new NDEBUG_UNUSED macro for variables only used in debug builds

.travis.yml
Hangs for no reason. We test OS X in GitHub Actions instead.
=> Travis: Removed OS X

libutils/json.c, libutils/json.h, tests/unit/data/sample.json, tests/unit/json_test.c
A function to go through all the elements in a given JSON and do
arbitrary operations on them. Useful for validation or any
functional-style computation on a JSON.
Ticket: ENT-6789
=> Add JsonWalk function

configure.ac
The headers are never used by libntech.
=> Remove Avahi headers checking from configure.ac

libutils/definitions.h, tests/unit/definitions_test.c
Unit test `test_metric_prefixes` caused integer overflow on systems
where an unsigned long is represented by 32 bits. Unsigned long long is
now used instead.
Ticket: None
=> Fix integer overflow in test_metric_prefixes

libutils/json.c, libutils/mustache.c
In an attempt to silence deliberate fall throughs
while being portable, an one line comment `/* fall through */`
was inserted at the end of the fall through-ing case.
=> CFE-3416: Fixed implicit-fallthrough compiler warnings on multiple files

configure.ac
This option was useful to confirm that libntech is built
with debug options. I though I might leave it in.
=> Added autoconf message for whether debug option is present

libutils/known_dirs.c
It should use an array in both the declaration and the
definition.
=> Fix ambiguous definition of GetDefaultDir_helper()

libutils/string_lib.c
No point in asserting that an unsigned value is >= 0.
=> Remove an always-true assert from StringCopy()

libutils/json.c, libutils/json.h, tests/unit/json_test.c
Function JsonArrayExtend moves elements from one JSON array to the end
of another JSON array. The first JSON array takes ownership of the
elements of the second JSON array. The second JSON array is freed from
memory.
Ticket: CFE-3648
Signed-off-by: larsewi <lars.erik.wik@northern.tech>
=> CFE-3648: Added function JsonArrayExtend to libntech

.github/workflows/asan_unit_tests.yml
These actions started failing with 404 messages sometimes, hope this helps.
=> Actions: Fix apt failures by running update

libutils/string_lib.h
Ignoring the return value of this function is always a bug:
* You cannot free the string - Memory leak
* It does nothing useful
=> Throw a warning / error when ignoring the return value of StringFormat()

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
Its primary use is the int policy function which
may accept floating point numbers as strings.
Ticket: None
=> Added StringDecimalToLong utility function

.travis.yml
Ticket: ENT-6713
Changelog: title
=> ENT-6713 Remove unused 3.10.x and 3.12.x from travis configuration

libutils/sequence.c, libutils/sequence.h, tests/unit/sequence_test.c
A function for replacing a value in a sequence without destroying
the replaced value. Useful for moving items away from a sequence
without unnecessary allocations (copying).
Ticket: ENT-5271
=> Add the SeqSoftSet() function

libutils/misc_lib.h, tests/unit/misc_lib_test.c
Added macro which can be used to support whitespace between
short-option-character and optional-argument.
Ticket: None
Signed-off-by: larsewi <lars.erik.wik@northern.tech>
=> Added utility macro for parsing short options

libutils/json.h, tests/unit/json_test.c
To check whether a given JsonElement is/isn't NULL or a JSON
'null' value.
Ticket: ENT-7434
=> Add NULL_JSON() and JSON_NOT_NULL() macros

libutils/logging.c, libutils/logging.h
Aside from global level which is used in all new threads for
system log and report (console) logging, it's useful to have an
ability to set the default global system log logging level to a
different value (e.g. to prevent noise in the system log). Each
thread can then use LoggingPrivSetLevels() to override those two
log levels if needed.
Ticket: ENT-7594
=> Add support for specifying global system log level

configure.ac
Debian is taking steps towards removing xml2-config in favour of pkg-config.
This means libntech will build without libxml2 support.
This patch modifies configure.ac to detect libxml2 via pkg-config, falling
back to xml2-config if pkg-config is not available.
The patch also integrates changes from ENT-9070.
Ticket: CFE-4023
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>
=> configure.ac: Enabled use of pkg-config to find libxml2

m4/cf3_gcc_flags.m4
AC_PREPROC_IFELSE outputs "checking how to run the C preprocessor..."
before executing its given preprocessor code.
Calling `AC_MSG_CHECKING(for HP-UX aC)' before AC_PREPROC_IFELSE results in
interrupted output, with the yes/no result of AC_MSG_RESULT appearing
on a separate line without context.
Ticket: CFE-4028
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>
=> cf3_gcc_flags.m4: Fixed order of `configure' output

libutils/man.c
Corrected some URLs which changed.
Changed http to https in some cases.
Ticket: ENT-9115
Changelog: title
=> ENT-9115: Fixed CFEngine man page URLs for all components

libutils/passopenfile.c
GCC 4.8.5-44 on CentOS 7 complains about this:
```
passopenfile.c: In function 'PassOpenFile_Put':
passopenfile.c:404:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
*(int*)CMSG_DATA(control_message) = descriptor;
^
```
because they have -fstrict-aliasing enabled by default.
=> Avoid dereferencing a type-punned pointer in passopenfile.cf

configure.ac
The CF3_WITH_LIBRARY and AC_CHECK_HEADERS were moved to outside of the check for with-libxml2=no
Ticket: CFE-4023
Changelog: title
=> CFE-4023: Fixed --with-libxml2=no case in configure.ac

.github/workflows/macos_unit_tests.yml, configure.ac
Ticket: ENT-9363
Changelog: title
together:
https://github.com/cfengine/libntech/pull/175
https://github.com/cfengine/core/pull/5180
=> ENT-9363: Fixed configure.ac to better recognize openssl with macos homebrew

libutils/json.c, libutils/json.h, tests/unit/json_test.c
JSON parser no longer accepts trailing bogus data (i.e. non-whitespace
characters up until the null-byte).
Merge together with https://github.com/cfengine/core/pull/5191
=> CFE-4080: JSON parser no longer accepts trailing bogus data

libutils/json.c, libutils/json.h, tests/unit/json_test.c
Added two functions `JsonObjectMergeDeep` and `JsonObjectMergeDeepInplace` for recursively merging JSON objects. The former merges two objects into a new object and has no side effects. The latter one merges one object into the other providing better performance when merging large data structures.
These functions were created for merging CMDB data (see ticket ENT-9956) as the `JsonMerge` function posed some limitations for this use case.
=> ENT-9956: Added functions for recursively merging JSON objects

configure.ac, libutils/logging.c, libutils/logging.h
- Added function to log structured messages
- CFEngine now uses structured logging
=> CFE-4185: Support structured logging in libntech

libutils/version_comparison.c, libutils/version_comparison.h, tests/unit/version_comparison_test.c
Will be used in the upcoming CFEngine policy function; `version_compare()`.
This function takes 3 arguments, 2 version numbers and an
operator between them, thus resembling an expression to evaluate.
(Is this version bigger than this version, etc.)
Internally it uses the exact same logic as we use for comparing the
currently installed CFEngine version, for the cf_version_minimum
and similar functions and macros.
=> CFE-3991: Added CompareVersionExpression() for comparing 2 version numbers

libutils/map.c
No need to iterate, a HashMap has the `load` field which contains the number of elements in the map.
Ticket: CFE-3043
Changelog: Complexity of MapSize() is now O(1) in all cases
=> Change MapSize() complexity to O(1) even if it's a hash map

libutils/buffer.c, tests/unit/regex_test.c
This is what CFEngine's regex_replace() function requires.
Ticket: ENT-10629
=> Ignore invalid backrefs in BufferSearchAndReplace()

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
The function joins a sequence of strings with an optional separator in between the elements.
=> Added new StringJoin() utility function

libutils/json-pcre.h, libutils/json.c, libutils/regex.c, libutils/regex.h.in
When migrating from PCRE to PCRE2 we had to make a change breaking API because all the functions working with REs were using the PCRE's type `pcre`. To avoid this change in the future, we define our own type `Regex` which we can later redefine without causing any API breakage.
This also requires a definition of `RegexDestroy()` for use instead of `pcre2_code_free()`.
Ticket: ENT-10629
Changelog: API working with regular expressions uses a custom
type Regex instead of pcre2_code directly
=> Define type Regex and implement RegexDestroy()

libutils/file_lib.c
=> Use the real leaf name (basename) when following links in the safe_*() functions

libutils/string_lib.h
After removing sequence.h include dependency from string_lib.h, it appears that there is no definition of `ssize_t` on SPARC 64 Solaris 11. Including sys/types.h should fix this issue.
=> Fixed `error: unknown type name ‘ssize_t’` on Solaris

libutils/file_lib.c
It was assumed that the potential mutation of the path (the input string) passed as an argument to basename(3) did not matter. However, this assumption was wrong, as the path is later used to determine whether or not the path points to a directory, using stat(2). In other words the mutation of the path caused stat(2) to fail, due to the basename being removed from it.
=> ENT-11434: Fixed bug where basename(3) modified its input string

libutils/json.c, libutils/json.h, tests/unit/json_test.c
Ticket: ENT-11450
Changelog: none
=> Fixed JsonCompare() function and switched to using it for json_test

.github/workflows/macos_unit_tests.yml
- **Fixed installation and PATH for libtool autoconf**
- **Use brew --prefix to locate LMDB, OpenSSL, and pcre**
Ported from https://github.com/cfengine/core/pull/5486
=> CFE-4385: Temporary fix for GH Action failures

configure.ac, libutils/file_lib.c
The FICLONE ioctl() is the most efficient way to copy a file inside one file system if available and supported. copy_file_range() is an alternative that can provide similar efficiency, but also only works inside one file system and requires us to take care of holes in files. sendfile() is very similar, but unline copy_file_range() it doesn't support reflinks.
Ticket: CFE-4380
Changelog: FileSparseCopy() now uses FICLONE ioctl(),
copy_file_range() or sendfile() on Linux
platforms (if available)
=> Use fancy and more efficient syscalls to copy (sparse) files on Linux

libutils/writer.c
Remove trailing whitespace after copyright in WriterWriteHelp().
=> libutils/writer: Removed spurious trailing whitespace

tests/unit/hash_test.c
Also, use the new API for initializing OpenSSL instead of the deprecated one.
=> Initialize OpenSSL before using it in hash_test

libutils/man.c, libutils/writer.c
Do not print placeholder for short option if there is none.
=> Fix short option output

tests/unit/string_lib_test.c
When building on Arch, I saw a few compilation errors of the form:
```
string_lib_test.c:873:40: error: passing argument 2 of ‘IsStringInArray’ from incompatible pointer type [-Wincompatible-pointer-types]
```
This small commit fixes them.
=> Make `array` & `new_array` const-correct in `test_is_string_in_array`.

libutils/file_lib.h
=> Fixed compiler warning for undefined reference of lstat

libutils/logging.h
=> Fixed compiler warning -Werror=enum-int-mismatch

libutils/file_lib.c
When calling `fdopen()` in `safe_fopen_create_perms()` using the `"wx"`
mode we get...
```
warning: Invalid parameter passed to C runtime function.
```
...on Windows. Looking in both Linux man pages and Win32 API, I see that
the mode argument `"x"` is not specified as a valid argument in either
of them. Hence, it is probably not supported. Maybe Unix systems simply
ignore it, while Windows returns error? Either way, I believe it is safe
to omit it, given that we already called `open()` with the `O_EXCL`
flag, and that we are getting the file stream from that same file
descriptor.
Ticket: ENT-12511
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11550)](https://ci.cfengine.com/job/pr- …
=> ENT-12511: Fixed bug where `cf-net.exe get` fails to create file

libutils/file_lib.c, libutils/file_lib.h, libutils/string_lib.c
Commit in core where this was moved is cfengine/core@3d914b512a9e92e0a06068934199f026c3761cd0
Ticket: CFE-3429
=> Moved GetRelocatedProcdirRoot() from libntech to core

.github/workflows/asan_unit_tests.yml, .github/workflows/cmake_examples.yml, .github/workflows/codeql.yml, .github/workflows/macos_unit_tests.yml, .github/workflows/unit_tests.yml
Ubuntu 20.04 runner is being deprecated.
> CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
Ticket: None
=> Bump deprecated versions in GitHub Actions workflows

.github/workflows/macos_unit_tests.yml, Makefile.am, configure.ac, m4/cf3_platforms.m4
Check for Homebrew if we're on Darwin and use brew's --prefix. Also use autoconf's macro for egrep to get rid of obsolescent warnings.
Ticket: CFE-4385
=> CFE-4385: Fix build on macOS

configure.ac
When a user specifies --with-something=/path/to/something in ./configure we don't want that to be overridden. In other words, we only want to do the automatic brew --prefix checking if the with_something variable is yes or check.
=> Adjusted logic for OS X brew and --with options to configure
