libutils/string_sequence.c, libutils/string_sequence.h, tests/unit/sequence_test.c
Needed for https://github.com/cfengine/core/pull/3893
=> Added SeqStringContains()

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
Split out into separate PR to make it easier to merge.
Originally from: https://github.com/cfengine/libntech/pull/21
=> Added StringMatchesOption()

libutils/alloc.h, libutils/buffer.c, libutils/buffer.h, libutils/csv_parser.c, libutils/file_lib.c, libutils/file_lib.h, libutils/mustache.c, libutils/regex.h, libutils/set.c, libutils/stack.c, libutils/stack.h, libutils/string_lib.h, libutils/string_sequence.c, libutils/unix_dir.c, libutils/writer.c, libutils/writer.h
Working on new project here:
https://github.com/olehermanse/cf-syntax
=> Cleaned up includes to rely on system / standard headers instead of config.h

libutils/file_lib.c, libutils/file_lib.h, libutils/logging.c, tests/unit/Makefile.am, tests/unit/file_lib_test.c, tests/unit/file_lock_test.c
Merge together:
https://github.com/cfengine/core/pull/3880
https://github.com/cfengine/enterprise/pull/556
https://github.com/cfengine/libntech/pull/27
=> File locking

libutils/file_lib.c
Copy-pasta failures and a missing include.
=> Fix issues in the file locking implementation for Windows

libutils/file_lib.c, tests/unit/file_lib_test.c
I wanna see a codecov increase!
=> Added unit tests for various file_lib functions

libutils/json-utils.c
Also refactored a little bit, to make the code more clear.
=> CFE-3210: Fixed memory leak in JSON / env file parsing

libutils/threaded_queue.c, libutils/threaded_queue.h, tests/unit/threaded_queue_test.c
A couple new functions for the ThreadedQueue data structure needed for my future work.
=> Extra ThreadedQueue functions

libutils/string_sequence.c, libutils/string_sequence.h, tests/unit/sequence_test.c
Probably need to add more varieties later, allowing FILE* streams
or accepting an already opened file, but this is good enough for
now (functionality needed + function needed to test).
=> ENT-5313: Added SeqStringReadFile() and SeqStringWriteFile()

libutils/json-utils.c
https://tracker.mender.io/browse/CFE-3256
=> CFE-3256: Added warning if CSV parser parses nothing from non-empty file

libutils/json-utils.c, libutils/json-yaml.c
=> CFE-3263: Various memory leak fixes with ASan

.travis.yml, configure.ac, libutils/Makefile.am, libutils/pcre_wrap.c, libutils/regex.c, libutils/string_lib.c, tests/unit/Makefile.am, tests/unit/string_lib_test.c, travis-scripts/before_install.sh, travis-scripts/script.sh
Merge together:
https://github.com/cfengine/libntech/pull/63
https://github.com/cfengine/core/pull/4105
=> Made it possible to build and test without OpenSSL and PCRE

libutils/sequence.c, libutils/sequence.h, tests/unit/sequence_test.c
With this function the 'Seq' structure can be used for building
pointer arrays.
=> Add a function for accessing sequence's data segment

libutils/sequence.c, libutils/sequence.h, tests/unit/sequence_test.c
Will be used for promise modules.
=> Added SeqSplit() function

libutils/definitions.h
This is supporting a core change https://github.com/cfengine/core/pull/4178
Ticket: ENT-5986
=> Added system group name defines

libutils/hash.c, libutils/json.c
=> hash.c, json.c: Replace trivial switch with if statements

libutils/file_lib.c, libutils/known_dirs.c, tests/unit/file_lock_test.c
merge together
https://github.com/cfengine/libntech/pull/66
https://github.com/cfengine/core/pull/4132
=> CFE-3285 cfengine for termux environment

libutils/file_lib.c, libutils/file_lib.h
Working with individual lines from a file is a common pattern and
sequence is a great data structure for storing such data.
Ticket: CFE-2945
=> Add a new function for reading lines from a file into a sequence

travis-scripts/script.sh
=> CFE-3389: Travis: Removed -Wno-pointer-sign flag

libutils/string_lib.h
Inlined functions for better readability.
=> Added StringContains() and StringContainsChar()

libutils/condition_macros.h, libutils/logging.c, libutils/passopenfile.c
See commit messages and comments for details.
=> CFE-3454: Added nt_static_assert()

libutils/logging.c
Prevent overflow in release builds by limiting buflen.
Always allocate buffer of CF_BUFSIZE.
Cleaned up asserts and scope of variables.
Removed pointless 16k constant.
This function is used to print network data, always <= 4096.
=> Refactored LogRaw to not use variable length array

libutils/logging.c
=> Fixed outdated comment

libutils/buffer.c, libutils/buffer.h, libutils/file_lib.c, libutils/hash.c, libutils/hash_map.c, libutils/hash_map_priv.h, libutils/json.c, libutils/misc_lib.c, libutils/regex.c, libutils/regex.h, libutils/sequence.h, libutils/string_lib.c, libutils/string_lib.h, libutils/string_sequence.c, libutils/threaded_queue.c, libutils/unicode.c
=> CFE-3415: Fixed some sign-compare warnings

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
Added functions StringToUlong, StringToUlongDefaultOnError,
StringToUlongExitOnError.
Ticket: None
=> Added utility functions converting string to ulong

configure.ac, libutils/known_dirs.c, libutils/known_dirs.h
=> Definitions for the data directory

libutils/misc_lib.h, tests/unit/misc_lib_test.c
=> Added absolute value macro

libutils/sequence.c, libutils/sequence.h
=> CFE-3417: Added strcmp wrapper to be used in sequence functions

libutils/json.c, libutils/json.h, libutils/set.c, libutils/set.h, tests/unit/set_test.c
For use in https://github.com/cfengine/core/pull/4638
=> Add JsonArrayToStringSet()

tests/unit/map_test.c
=> CFE-3643: Added unit tests to increase coverage of ArrayMap

libutils/known_dirs.c
Should be "WORKDIR/data", not "default/data".
=> Fix default 'data' directory path for root

libutils/json.h
=> Fixed TODO in JsonObjectGetAsBool docs

libutils/string_lib.c, libutils/string_lib.h, tests/unit/string_lib_test.c
Similar to StringReplace() but only replacing the first N
occurences.
Ticket: ENT-8289
Chagelog: None
=> Add a new function StringReplaceN()

libutils/alloc.h, tests/unit/alloc_test.c
No need to write the for loop over and over in all places where
it's needed.
Ticket: ENT-8307
=> Add free_array_items() inline function

.github/workflows/macos_unit_tests.yml
Copied from core: https://github.com/cfengine/core/blob/master/.github/workflows/macos_unit_tests.yml
=> Fixed MacOS unit tests in GH Actions

.github/workflows/unit_tests.yml
=> Add unit tests to Github Actions

libutils/set.h, tests/unit/set_test.c
`StringSetAddF()` formats a string and adds it to the string set.
=> Added `StringSetAddF()` function to libntech

.github/workflows/static_check.yml, .gitignore, Makefile.am, configure.ac, libcompat/inet_pton.c, libutils/glob_lib.c, tests/static-check/Makefile.am, tests/static-check/cppcheck_suppressions.txt, tests/static-check/run.sh, tests/static-check/run_checks.sh
blocks CFE-3429 and https://github.com/cfengine/core/pull/5702
=> Add static-check and fix a few issues
